# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 027dd3e5c5bfad0316a656469b85a4ba2a3ef455e3c405409084db8a746b1c43ff12fed6001853325663d97da1c7e929ca4fe2bbb831066c723e2fb35fdd28d7

test:
  secret_key_base: 85a382f711570fa50233816629fde0f1af1dd4419ea2637311c75578e1b94e92728e1a5fbf0b4d20e3aa3c10ca691b7deb55cff625e3a7f25cfde5988655c26a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
